### ISSUE TITLE
Doesn't work without mysql (docs say otherwise).

### ISSUE THREAD

**Issue by tim-seoss** [sma-bluetooth/sma-bluetooth#138]
When leaving the mysqlXXX config items blank, the software still attempts to connect to a mysql server.

**Comment by stephenbcollier** [comment]
There will be a new version during next week which will address some of
those issues including 138. I am currently testing it.

**Comment by koenr** [comment]
I don't know if it is related, but it also doesn't work with MariaDB on Synology.

**Comment by tim-seoss** [comment]
Ah, OK, currently patching this myself, as I could really do with it up and running today.  Any chance you keep the work-in-progress up on github in a different branch?

**Comment by tim-seoss** [comment]
Re MariaDB, this is unrelated.

**Comment by tim-seoss** [comment]
FWIW, fix here:

https://github.com/tim-seoss/sma-bluetooth

**Comment by stephenbcollier** [comment]
I'm using Maria db on El 7 to develop it. What doesn't work?

Cheers
Stephen

**Comment by koenr** [comment]
The compiling of the software on the Synology (arm processor).  I'll create
a new and well documented report for it.
Thank you for your interest.
What is El 7?

2015-05-09 12:19 GMT+02:00 stephenbcollier <notifications@github.com>:

> I'm using Maria db on El 7 to develop it. What doesn't work?
>
> Cheers
> Stephen
