### ISSUE TITLE
dual Sunny Boy SB3300TL HC sniffing data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sma-bluetooth/sma-bluetooth#24]
```
Please find attached data from my dual setup of SB 3300. Sniffed with 
USBsniffer. 

Marcus
```

Original issue reported on code.google.com by `marcus.p...@gmail.com` on 2 May 2011 at 3:24

Attachments:
* [USBLog2.usblog](https://storage.googleapis.com/google-code-attachments/sma-bluetooth/issue-24/comment-0/USBLog2.usblog)

**Comment by stephenbcollier** [comment]
It should be fixed I think it the crc applied to an incorrect area of the code
