### ISSUE TITLE
USB Sniff results - SB3000TL-20

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sma-bluetooth/sma-bluetooth#26]
```
Here is the log from my sniff.
I hope you'll find why I can't run sma-bluetooth with my inverter.
```

Original issue reported on code.google.com by `buzzi.la...@gmail.com` on 5 May 2011 at 8:44

Attachments:
* [usbsnoop.log](https://storage.googleapis.com/google-code-attachments/sma-bluetooth/issue-26/comment-0/usbsnoop.log)

**Comment by stephenbcollier** [comment]
Next version will not need codes
