### ISSUE TITLE
Loading past data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sma-bluetooth/sma-bluetooth#38]
```
I just set up SMA-Bluetooth. Loaded the data to MySQL - all good.
How can I load all of the data from MySQL to PVOutput.org (have about 6 
months)? 
```

Original issue reported on code.google.com by `fok...@gmail.com` on 13 Sep 2011 at 6:28

**Comment by stephenbcollier** [comment]
smatool -repost is for this but it only sends summary daily data as PVOutput only goes back 14 days for live data
